test:
  adapter: 'sqlite3'
  database: ':memory:'
  encoding: 'utf8'
development:
  adapter: 'sqlite3'
  database: 'db/development.sqlite3'
  encoding: 'utf8'
production:
  adapter: 'sqlite3'
  database: 'db/production.sqlite3'
  encoding: 'utf8'
